### ISSUE TITLE
Is there any progress in biblatex-japanese?

### ISSUE THREAD

**Issue by wangjunqi** [kmaed/biblatex-japanese#2]
Hello, I am really looking forward to this package. Since you haven't updated these files for almost seven months, so please allow me to consult the progress of this project. 

Good luck.

**Comment by kmaed** [comment]
I'm sorry for the inconvenience, but I'm now very busy for my daily works. If you can contribute to this package, it is very welcome. An easy way is that you fork this repository, commit changes, and sent pull requests.

I began this project to create a framework for biblatex to support Japanese language. But you might be interested in CJK languages support, not only Japanese language. Since I don't have any knowledge on Chinese or Korean bibliographies, if you have any idea for CJK languages support, it is also very welcome.

Thank you.
